# Generated by Django 5.2.8 on 2026-01-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=True,
                help_text="Отметьте, чтобы продукт был виден в каталоге",
                verbose_name="Опубликовано",
            ),
        ),
    ]
